routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('base', 'BaseController');

// Route::get('member', 'MemberController@store');
Route::get('members', 'MemberController@create');
Route::post('member/{base_id}', 'MemberController@store')->name('member');

Route::get('planes', 'PlaneController@create');
Route::post('plane', 'PlaneController@store')->name('plane');

Route::get('pilots', 'PilotController@create');
Route::post('pilot/{base_id}', 'PilotController@store')->name('pilot');
Route::get('piloto/{id}', 'PilotController@show');

Route::get('fligths', 'FligthController@create');
Route::post('fligth', 'FligthController@store')->name('fligth');

// Route::post('pilot', ['as' => 'Pilot.store', 'base' => 'PilotController@store']);

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina Principal</title>
</head>
<body>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    @foreach($bases as $base)
      <th scope="row">{{$base->name}}</th>
      <td>
      <a href="http://127.0.0.1:8000/planes" style="border: none; background: white;" name="detalles"><img src="/images/avion.png" style="background: white; height: 20px; width: 20px;" title="Agregar avion"></a>
        <a href="http://127.0.0.1:8000/pilots?idbase={{$base->id}}" style="border: none; background: white;" name="detalles"><img src="/images/piloto.png" style="background: white; height: 20px; width: 20px;" title="Agregar pilotos"></a>
        <a href="http://127.0.0.1:8000/members?baseid={{$base->id}}" style="border: none; background: white;" name="detalles"><img src="/images/comunidad.png" style="background: white; height: 20px; width: 20px;" title="Agregar miembros"></a>
        <a href="http://127.0.0.1:8000/fligths?" style="border: none; background: white;" name="detalles"><img src="/images/vuelo.png" style="background: white; height: 20px; width: 20px;" title="Agregar vuelos"></a>
        <a href="/base/{{$base->id}}" style="border: none; background: white;" name="detalles"><img src="/images/ver.png" style="background: white; height: 20px; width: 20px;" title="Ver Detalles"></a>
        <a href="/base/{{$base->id}}/edit" style="border: none; background: white;" name="detalles"><img src="/images/actualizar.png" style="background: white; height: 20px; width: 20px;" title="Actualizar"></a>
        <form action="{{ route('base.destroy', $base->id)}}" method="POST" class="form form-group">
        @method("DELETE")
        @csrf
        <button type="submit" class="btn btn-primary" style="border:none;background:white;"><img src="/images/eliminar.png" style="background: white; height:20px; width:20px;" title="Eliminar">
        </button>
        </form>
      </td>
    </tr>
    @endforeach
    <a href="http://127.0.0.1:8000/base/create" class="btn btn-danger">Agregar Base</a><br><br>
  </tbody>
</table>
</div>
</body>
</html>

resources/views/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles</title>
</head>
<body>

<div class="container">
<table class="table">
  <thead class="thead-dark">
  <tr><p class="h3">Aviones</p>
      <th scope="col">Codigo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    @if(count($base->planes)>0)
    @foreach($base->planes as $plane)
      <td>{{$plane->code}}</td>
    </tr>
    @endforeach
    @else
    <h3>La base no tienen aviones</h3>
    @endif
  </tbody>
</table>
<hr>
</div>


<div class="container">
<table class="table">
  <thead class="thead-dark">
  <tr><p class="h3">Pilotos</p>
      <th scope="col">Codigo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    @if(count($base->pilots)>0)
    @foreach($base->pilots as $pilot)
      <td>{{$pilot->code}} <a href="/piloto/{{$pilot->id}}" class="btn btn-primary">Ver Vuelos del Piloto</a></td>
    </tr>
    @endforeach
    @else
    <h3>La base no tiene Pilotos</h3>
    @endif
  </tbody>
</table>
<hr>
</div>


<div class="container">
<table class="table">
  <thead class="thead-dark">
  <tr><p class="h3">Tripulacion</p>
      <th scope="col">miembros</th>
      <th scope="col">Codigo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    @if(count($base->members)>0)
    @foreach($base->members as $miembro)
      <td>{{$miembro->name}}</td>
      <td>{{$miembro->code}}</td>
    </tr>
    @endforeach
    @else
    <h3>La base no tiene Tripulacion</h3>
    @endif
  </tbody>
</table>
<a href="http://127.0.0.1:8000/base" class="btn btn-primary">Volver</a>
</div>

</body>
</html>