routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('base', 'BaseController');

// Route::get('member', 'MemberController@store');
Route::get('members', 'MemberController@create');
Route::post('member/{base_id}', 'MemberController@store')->name('member');

Route::get('planes', 'PlaneController@create');
Route::post('plane', 'PlaneController@store')->name('plane');

Route::get('pilots', 'PilotController@create');
Route::post('pilot/{base_id}', 'PilotController@store')->name('pilot');
Route::get('piloto/{id}', 'PilotController@show');

Route::get('fligths', 'FligthController@create');
Route::post('fligth', 'FligthController@store')->name('fligth');

// Route::post('pilot', ['as' => 'Pilot.store', 'base' => 'PilotController@store']);

resources/views/bases/add_base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar</title>
</head>
<body>
<div class="container">
<form action="{{route('base.store')}}" method="post">
    {{ csrf_field() }}
  <div class="form-group">
    <label for="exampleInputEmail1">Nombre: </label>
    <input type="text" class="form-control" name="name" placeholder="Ejemplo: Base Principal">
    <small id="emailHelp" class="form-text text-muted">Ingrese el nombre de la base</small><br>
  </div>
  <button type="submit" class="btn btn-primary">Guardar</button><br><br>
  <a href="http://127.0.0.1:8000/base" class="btn btn-primary">Volver</a>
</form>
</div>
</body>
</html>

resources/views/bases/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar</title>
</head>
<body>
<div class="container">
<form action="/base/{{$base->id}}" method="post">
@method('PUT')
    {{ csrf_field() }}
  <div class="form-group">
    <label for="exampleInputEmail1">Nombre: </label>
    <input type="text" class="form-control" name="name" value="{{$base->name}}">
    <small id="emailHelp" class="form-text text-muted">Ingrese el nombre de la base</small><br>
  </div><br>
  <button type="submit" class="btn btn-primary">Actualizar</button><br><br><a href="http://127.0.0.1:8000/base" class="btn btn-primary">Volver</a>
</form>
</div>
</body>
</html>